### ISSUE TITLE
List of gb_args options

### ISSUE THREAD

**Issue by PietroBernardiIT** [arogozhnikov/hep_ml#35]
Hi,
I'm using the Gradient Boosted Reweighter object GBReweighter from the hep_ml.reweight package.
I was wondering if it could be possible to have the list of the possible options that can be passed to the GBReweighter via the "gb_args" dictionary.

Thanks!
Pietro

**Comment by arogozhnikov** [comment]
Hi, thanks for reminding.

I'll add description in the next release, but so far: 
`gb_args` can contain any parameters that could be passed to `hep_ml.gradientboosting.UGradientBoostingClassifier` constructor for the except of loss and parameters explicitly available in GBReweighter interface.
