### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mayou36** [arogozhnikov/hep_ml#48]
Hey,
what do you think of a new release? The last release is over a year ago and some nice things have been added since (like loss_regularization parameter etc.).

Moreover, it is very unhandy to specify the github version as a pip dependency (most of all as an optional dependency), a new pip version would be really great.

**Comment by arogozhnikov** [comment]
Hi Jonas, 

thanks for reminding. 
I've just uploaded hep_ml==0.5 to PyPI, so it should be available with `pip install hep_ml`.
