### ISSUE TITLE
Multidimensional reweighting

### ISSUE THREAD

**Issue by mschubi** [arogozhnikov/hep_ml#54]
Hi,

I'm using hep_ml to perform a multidimensional reweighting of a MC sample and it is working really well. I have a question, to which I've not been able to find an answer in the paper (https://arxiv.org/pdf/1608.05806.pdf) or in the documentation (https://arogozhnikov.github.io/hep_ml/reweight.html).

The multidimensional space is split in large bins by optimising a symmetrised chi2. But are those bins multidimensional or 1-dimensional ? In other words, is hep_ml reweighting 1D distributions iteratively ? Or is it reweighting multidimensional distributions directly ?

Cheers,
Maxime

**Comment by arogozhnikov** [comment]
Hi, 

> But are those bins multidimensional or 1-dimensional ?

Bins are miltidimensional. Bin corresponds to leaf of a tree, if tree has depth > 1, bins are multidimensional.

**Comment by mschubi** [comment]
Hi Alex,

Oh I see. I was still thinking in terms of 1D variables being cut in 1D bins at each step of the BDT, but all the nodes are then combined to form the region that is reweighted, making it multidimensional.

Thanks a lot for your quick answer. 
Cheers,
Maxime
