### ISSUE TITLE
sPlot returns NAN sWeights

### ISSUE THREAD

**Issue by marthaisabelhilton** [arogozhnikov/hep_ml#58]
I am currently trying to use help_ml splot and am getting some sWeights as nan. I am using a sample of ~1.4M events and this seems to be happening after event ~200k. I have checked the signal and background probabilities and these look reasonable. I have also checked the sWeights before event ~200k and these also look reasonable. I have checked the sWeighted signal and background distributions for a relevant pT variable and these also look ok.

So I am wondering is there some reason they will not be calculated correctly after a certain event? Any help would be much appreciated.

![image](https://user-images.githubusercontent.com/34545619/53097187-2310b080-3521-11e9-8fe6-42e2ed3c89b6.png)
![image](https://user-images.githubusercontent.com/34545619/53097194-2a37be80-3521-11e9-85b4-d62c890512f8.png)

![image](https://user-images.githubusercontent.com/34545619/53097205-30c63600-3521-11e9-978c-0a6a6191f2ab.png)

**Comment by alexpearce** [comment]
What fraction of events get a NaN value? You should inspect the input data for the entries that get a NaN weight asit might be that, for example, you're feeding the log of some column which is negative for a handful of events.

**Comment by arogozhnikov** [comment]
I agree with @alexpearce 

I'd expect problems with input - please check range of both input probs and weights, and presence of NaNs or infty values.

**Comment by marthaisabelhilton** [comment]
Sorry for the spam I realised the problem was with the indexing of the dataframes - I was trying to copy the sWeights dataframe to an existing dataframe and the indexes where not matching so the empty values were being filled with nans.
