### ISSUE TITLE
Persistify GBReweighter instance

### ISSUE THREAD

**Issue by acampove** [arogozhnikov/hep_ml#64]
Hello Alex,

I am using the GBReweighter class:

https://arogozhnikov.github.io/hep_ml/reweight.html?highlight=gbreweighter#hep_ml.reweight.GBReweighter.predict_weights

and I would like to know if there is a native way to persistify an instance of this class so that it can be used to predict_weights afterwards. I cannot find anything native in the documentation and I was thinking that maybe something like pickle might work.

Cheers.

**Comment by arogozhnikov** [comment]
Hi @acampove , 
yes, pickle is the right way to store estimators from `hep_ml` including GBReweighter.
