### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by chrisburr** [arogozhnikov/hep_ml#66]
Currently the conda-forge package of hep_ml fails due to the deprecations in sklearn that werre fixed by #62. Would it be possible to make a new release so conda-forge can be updated?

Tangentially related, I noticed the v0.6.1 release on PyPI doesn't have a corresponding tag here.

**Comment by arogozhnikov** [comment]
Hi @chrisburr, thanks for reporting. I've added github tag for 0.6.1, and published a new release to pypi.
