### ISSUE TITLE
GBReweights seems to be not working in my case 

### ISSUE THREAD

**Issue by Soumyatifr** [arogozhnikov/hep_ml#84]
Dear experts,
I am using GBreweighting to reweight control region (original) data to a signal data (target data), roughly the statistics of these two regions are : for control region ~ 1.5M and for signal region 25K, and I am using 5-7 variables for the reweighing, the individual KS score is high for only one variable around 0.15 and for the rest of the varaivles KS score < 0.05. 
The model I am using : 
```
reweighter = reweight.GBReweighter(n_estimators=30, learning_rate=0.1, max_depth=3, min_samples_leaf=100,
                                   gb_args={'subsample': 0.4}) 
```
There is no change of the variables before and after the reweighting, the two set of plots are attached here. 
Could you please check where I have made the mistake or where I need mofification to make the GBReweighting method useful.  
Thanks in advance,
Soumya
Before reweighting
![before_reweighting](https://github.com/arogozhnikov/hep_ml/assets/46934323/854dac52-3272-49ae-9d9d-7e010089ce03)
After reweighting
![after_reweighting](https://github.com/arogozhnikov/hep_ml/assets/46934323/2be84b11-caf6-4b01-978a-006a02c37ee1)

**Comment by arogozhnikov** [comment]
Hi @Soumyatifr , interesting case. Can't guess the reason, but for sanity check - how about leaving only one variable ('HT') in training and see if it gets corrected?

**Comment by Soumyatifr** [comment]
Dear Alex @arogozhnikov,
Thanks for your very prompt reply, I have checked with only "HT" variable but still it doesn't want, it would be very hgelpful for me, if you can see the code [1] and the two root files , which I have uploaded to my google drive[2]. 
[1] https://github.com/Soumyatifr/GBReweighting/blob/main/bdt_reweighet.ipynb
[2] https://drive.google.com/drive/folders/1ZCkF0V58O_fC1gnKqFRL-HYaE97mYwbe?usp=sharing

**Comment by arogozhnikov** [comment]
@Soumyatifr 
just ran your code with single HT variable, and it clearly has strong improvements:

before reweighting
![test_before](https://github.com/arogozhnikov/hep_ml/assets/6318811/a9e830e2-9187-417b-9255-70e4eae1d1c7)

after reweighting
![test_after](https://github.com/arogozhnikov/hep_ml/assets/6318811/cad38d57-d266-4c76-9b83-d6e332b32fca)

hopefully it looks similar in your env, otherwise there is some problem with package versions.

**Comment by arogozhnikov** [comment]
ok, assume that helped
